apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "recycler.fullname" . }}-manager-role
  namespace: {{ include "recycler.namespace" . }}
  labels:
  {{- include "recycler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers/finalizers
  verbs:
  - update
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "recycler.fullname" . }}-manager-rolebinding
  labels:
  {{- include "recycler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "recycler.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "recycler.fullname" . }}-controller-manager'
  namespace: '{{ include "recycler.namespace" . }}'
