apiVersion: v1
kind: Service
metadata:
  name: {{ include "recycler.fullname" . }}-controller-manager-metrics-service
    namespace: {{ include "recycler.namespace" . }}
  labels:
    control-plane: controller-manager
  {{- include "recycler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
    {{- include "recycler.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}
