apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "recycler.fullname" . }}-recycler-editor-role
  namespace: {{ include "recycler.namespace" . }}
  labels:
  {{- include "recycler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers/status
  verbs:
  - get
