apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "recycler.fullname" . }}-controller-manager
  namespace: {{ include "recycler.namespace" . }}
  labels:
  {{- include "recycler.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
