apiVersion: recycler.theonlywaye.com/v1alpha1
kind: Recycler
metadata:
  name: user-profile-recycler
  namespace: profiles-framework
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: palms-user-profile
  averageCpuUtilizationPercent: 1
  recycleDelaySeconds: 300
