# permissions for end users to view recycles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: recycler
    app.kubernetes.io/managed-by: kustomize
  name: recycle-viewer-role
rules:
- apiGroups:
  - recycler.k8s.io
  resources:
  - recycles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - recycler.k8s.io
  resources:
  - recycles/status
  verbs:
  - get
