# permissions for end users to view recyclers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: recycler
    app.kubernetes.io/managed-by: kustomize
  name: recycler-viewer-role
rules:
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers/status
  verbs:
  - get
