# permissions for end users to edit recycles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: recycler
    app.kubernetes.io/managed-by: kustomize
  name: recycle-editor-role
rules:
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recycles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recycles/status
  verbs:
  - get
