apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "recycler-debug.fullname" . }}-manager-role
  labels:
  {{- include "recycler-debug.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers/finalizers
  verbs:
  - update
- apiGroups:
  - recycler.theonlywaye.com
  resources:
  - recyclers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "recycler-debug.fullname" . }}-manager-rolebinding
  labels:
  {{- include "recycler-debug.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "recycler-debug.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "recycler-debug.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
