name: Build and Push Recycler Operator image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
        - main
  release:
    types: [published]

jobs:
  semver:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      current_version: ${{ steps.semver.outputs.current }}
      next_version: ${{ steps.semver.outputs.nextStrict }}
      release_upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: ${{ github.head_ref || github.ref_name }}
        patchAll: true
        majorList: "breaking,major"

  build:
    needs: [semver]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install Operator SDK
      run: make operator-sdk

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Operator
      run: make docker-buildx IMG=theonlywaye/recycler:${{ needs.semver.outputs.next_version }} VERSION=${{ needs.semver.outputs.next_version }}
      #run: make docker-build docker-push IMG=theonlywaye/recycler:${{ needs.semver.outputs.next_version }} VERSION=${{ needs.semver.outputs.next_version }}

  release:
    needs: [semver, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create Release
      uses: softprops/action-gh-release@v2
      id: release
      with:
        draft: false
        make_latest: true
        name: ${{ needs.semver.outputs.next_version }}
        tag_name: ${{ needs.semver.outputs.next_version }}
        body: ${{ steps.changelog.outputs.changes }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        fromTag: ${{ needs.semver.outputs.current_version }}
        toTag: ${{ needs.semver.outputs.next_version }}

    - name: Commit CHANGELOG.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: 'docs: update CHANGELOG.md for ${{ needs.semver.outputs.next_version }} [skip ci]'
        file_pattern: CHANGELOG.md

    - name: Trigger Helm Chart Release Workflow
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/dispatches \
        -d '{"event_type":"helm_chart_release","client_payload":{"next_version":"${{ needs.semver.outputs.next_version }}", "upload_url":"${{ steps.release.outputs.upload_url }}"}}'

  cleanup:
    needs: [semver, build, release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check and Delete Docker Image
        run: |
          IMAGE="theonlywaye/recycler:${{ needs.semver.outputs.next_version }}"
          if docker manifest inspect $IMAGE > /dev/null 2>&1; then
            echo "Docker image $IMAGE exists. Deleting..."
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
            docker rmi $IMAGE || true
          else
            echo "Docker image $IMAGE does not exist. Skipping deletion."
          fi

      - uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true # default: false
          tag_name: v${{ needs.semver.outputs.next_version }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset Branch to Initial Commit
        run: |
          git fetch origin
          git reset --hard ${{ github.sha }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
