name: Build and Push Operator SDK Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version-file: 'go.mod'

    - name: Verify Go Version
      run: go version

    - name: Install Operator SDK
      run: make operator-sdk

    - name: Build Operator
      run: make docker-buildx
