name: Build and Push Recycler Operator image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
        - main
  release:
    types: [published]

jobs:
  tag:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      next_version: ${{ steps.semver.outputs.nextStrict }}
      release_upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: ${{ github.head_ref || github.ref_name }}
        patchAll: true
        majorList: "breaking,major"

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ steps.semver.outputs.current }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      id: release
      with:
        allowUpdates: true
        draft: false
        makeLatest: true
        name: ${{ steps.semver.outputs.next }}
        tag: ${{ steps.semver.outputs.next }}
        body: ${{ steps.changelog.outputs.changes }}
        token: ${{ github.token }}

    - name: Commit CHANGELOG.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
        file_pattern: CHANGELOG.md

  build:
    needs: [tag]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install Operator SDK
      run: make operator-sdk

    - name: Install Helmify
      run: make helmify

    - name: Generate Helm Charts
      run: make helm

    - name: Update Helm Chart Tag
      run: |
        sed -i "s/tag: .*/tag: ${{ needs.tag.outputs.next_version }}/" helm-charts/recycler/values.yaml

    - name: Package Helm Chart
      run: |
        mkdir -p ./releases
        helm package ./helm-charts/recycler --destination ./releases
        helm repo index ./releases --url https://${{ github.repository_owner }}.github.io/${{ github.repository }}/releases

    - name: Commit and Push Releases
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./releases
        git commit -m "Add Helm chart to releases [skip ci]"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Operator
      #run: make docker-buildx IMG=theonlywaye/recycler:${{ needs.tag.outputs.next_version }} VERSION=${{ needs.tag.outputs.next_version }}
      run: make docker-build docker-push IMG=theonlywaye/recycler:${{ needs.tag.outputs.next_version }} VERSION=${{ needs.tag.outputs.next_version }}

    - name: Upload Helm Chart to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.tag.outputs.release_upload_url }}
        asset_path: ./releases/recycler-*.tgz
        asset_name: recycler-${{ needs.tag.outputs.next_version }}.tgz
        asset_content_type: application/gzip

  cleanup:
    needs: [tag, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true # default: false
          tag_name: v${{ needs.tag.outputs.next_version }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
