name: Update changelog

on:
  repository_dispatch:
    types:
      - update_changelog

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.event.client_payload.tag_name }}

      - name: Update Release with Changelog
        uses: softprops/action-gh-release@v2
        id: release
        with:
            name: ${{ github.event.client_payload.tag_name }}
            body: ${{ steps.changelog.outputs.changes }}
            tag_name: ${{ github.event.client_payload.tag_name }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.event.client_payload.tag_name }} [skip ci]'
          file_pattern: CHANGELOG.md

      - name: Trigger Helm Chart Release Workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"helm_chart_release","client_payload":{"next_version":"${{ github.event.client_payload.tag_name }}", "upload_url":"${{ steps.release.outputs.upload_url }}", "release_url":"${{ steps.release.outputs.url }}", "release_id":"${{ steps.release.outputs.id }}"}}'
