name: Helm Chart Release

on:
  repository_dispatch:
    types: [helm_chart_release]

jobs:
  helm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Update Chart Version
      run: |
        sed -i "s/^version: .*/version: ${{ github.event.client_payload.next_version }}/" helm-charts/recycler/Chart.yaml
        sed -i "s/^appVersion: .*/appVersion: \"${{ github.event.client_payload.next_version }}\"/" helm-charts/recycler/Chart.yaml

    - name: Update Helm chart image tag
      run: |
        sed -i "s/tag: .*/tag: ${{ github.event.client_payload.next_version }}/" helm-charts/recycler/values.yaml

    - name: Package Helm Chart
      run: |
        mkdir -p ./releases
        helm package ./helm-charts/recycler --destination ./releases

    - name: Authenticate with GHCR
      run: |
        echo "${{ github.token }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

    - name: Push Helm Chart to GitHub Container Registry
      run: |
        CHART_FILE=releases/recycler-${{ github.event.client_payload.next_version }}.tgz
        echo "Pushing $CHART_FILE to GHCR..."
        helm push $CHART_FILE oci://ghcr.io/${{ github.repository_owner }}/charts

    - name: Authenticate with Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login registry-1.docker.io --username ${{ vars.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Helm Chart to GitHub Container Registry
      run: |
        CHART_FILE=releases/recycler-${{ github.event.client_payload.next_version }}.tgz
        echo "Pushing $CHART_FILE to Docker hub..."
        helm push $CHART_FILE oci://theonlywaye/recycler

    - name: Link GHCR and Docker Hub Packages to Release
      run: |
        GHCR_PACKAGE_URL="https://ghcr.io/${{ github.repository_owner }}/charts/recycler:${{ github.event.client_payload.next_version }}"
        DOCKERHUB_PACKAGE_URL="https://hub.docker.com/r/theonlywaye/recycler/tags?page=1&name=${{ github.event.client_payload.next_version }}"
        CURRENT_NOTES=$(gh release view ${{ github.event.client_payload.next_version }} --json body -q ".body")
        UPDATED_NOTES="${CURRENT_NOTES}\n\nHelm chart packages available at:\n- GHCR: ${GHCR_PACKAGE_URL}\n- Docker Hub: ${DOCKERHUB_PACKAGE_URL}"
        gh release edit ${{ github.event.client_payload.next_version }} --notes "${UPDATED_NOTES}"
        echo "Appended GHCR and Docker Hub package URLs to release notes."

  pages:
    needs: [helm]
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
