name: Lint

on:
  # push:
  #   branches-ignore:
  #     - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod

      - name: Run go fmt
        run: |
          go fmt ./...

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: 'chore: go fmt [skip ci]'

      - name: Run linter
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: latest
