name: Tests

on:
  # push:
  #   branches-ignore:
  #     - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test

      - name: Generate HTML coverage report
        run: go tool cover -html=cover.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: coverage-report
          path: coverage.html
